on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          # this assumes that you have created a personal access token
          # (PAT) and configured it as a GitHub action secret named
          # `MY_RELEASE_PLEASE_TOKEN` (this secret name is not important).
          token: ${{ secrets.RELEASE_TOKEN }}
          # this is a built-in strategy in release-please, see "Action Inputs"
          # for more options
          release-type: simple
  
  auto-approve:
      needs: release-please
      if: ${{ needs.release.outputs.pr }}
      runs-on: ubuntu-latest
      steps:
        - name: Auto approve PR
          uses: hmarr/auto-approve-action@v3
          with:
            github-token: ${{ secrets.RELEASE_TOKEN }}
            pull-request-number: ${{ needs.release.outputs.pr }}

  auto-merge:
    needs: [release-please, auto-approve]
    if: ${{ needs.release.outputs.pr }}
    runs-on: ubuntu-latest
    steps:
      - name: Auto merge PR
        uses: peter-evans/auto-merge@v4
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          pull-request: ${{ needs.release.outputs.pr }}
          merge-method: squash
          delete-branch: true
